spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:8081/ajosures
spring.datasource.username=postgres
spring.datasource.password=GodHelpme@2005

spring.jpa.hibernate.ddl-auto=update

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration